
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLOSEINTERVAL CLOSERANGE FLOAT GOPENINTERVAL GROUPSPLITTER INTEGER KWSIGN MINUS OPENINTERVAL OPENRANGE STRING VNAMEsentence : VNAME\n                | VNAME args\n                | VNAME kwargs\n                | VNAME args kwargskwargs : kwargs kwarg\n            | kwargkwarg : kwflag\n            | kwflag argkwflag : KWSIGN VNAMEargs : args arg\n            | argarg : STRING\n            | number\n            | crange\n            | rinterval\n            | grintervalcrange : OPENRANGE number GROUPSPLITTER number GROUPSPLITTER rinterval CLOSERANGE\n                | OPENRANGE number GROUPSPLITTER number GROUPSPLITTER number CLOSERANGE\n                | OPENRANGE number GROUPSPLITTER number CLOSERANGEgrinterval : GOPENINTERVAL number GROUPSPLITTER number CLOSEINTERVALrinterval : OPENINTERVAL number GROUPSPLITTER number CLOSEINTERVALnumber : INTEGER\n                | FLOAT'
    
_lr_action_items = {'VNAME':([0,18,],[2,26,]),'$end':([1,2,3,4,5,6,7,8,9,10,11,12,13,14,19,20,21,22,26,34,35,36,39,40,],[0,-1,-2,-3,-11,-6,-12,-13,-14,-15,-16,-7,-22,-23,-4,-10,-5,-8,-9,-19,-21,-20,-18,-17,]),'STRING':([2,3,5,7,8,9,10,11,12,13,14,20,26,34,35,36,39,40,],[7,7,-11,-12,-13,-14,-15,-16,7,-22,-23,-10,-9,-19,-21,-20,-18,-17,]),'INTEGER':([2,3,5,7,8,9,10,11,12,13,14,15,16,17,20,26,27,28,29,33,34,35,36,39,40,],[13,13,-11,-12,-13,-14,-15,-16,13,-22,-23,13,13,13,-10,-9,13,13,13,13,-19,-21,-20,-18,-17,]),'FLOAT':([2,3,5,7,8,9,10,11,12,13,14,15,16,17,20,26,27,28,29,33,34,35,36,39,40,],[14,14,-11,-12,-13,-14,-15,-16,14,-22,-23,14,14,14,-10,-9,14,14,14,14,-19,-21,-20,-18,-17,]),'OPENRANGE':([2,3,5,7,8,9,10,11,12,13,14,20,26,34,35,36,39,40,],[15,15,-11,-12,-13,-14,-15,-16,15,-22,-23,-10,-9,-19,-21,-20,-18,-17,]),'OPENINTERVAL':([2,3,5,7,8,9,10,11,12,13,14,20,26,33,34,35,36,39,40,],[16,16,-11,-12,-13,-14,-15,-16,16,-22,-23,-10,-9,16,-19,-21,-20,-18,-17,]),'GOPENINTERVAL':([2,3,5,7,8,9,10,11,12,13,14,20,26,34,35,36,39,40,],[17,17,-11,-12,-13,-14,-15,-16,17,-22,-23,-10,-9,-19,-21,-20,-18,-17,]),'KWSIGN':([2,3,4,5,6,7,8,9,10,11,12,13,14,19,20,21,22,26,34,35,36,39,40,],[18,18,18,-11,-6,-12,-13,-14,-15,-16,-7,-22,-23,18,-10,-5,-8,-9,-19,-21,-20,-18,-17,]),'GROUPSPLITTER':([13,14,23,24,25,30,],[-22,-23,27,28,29,33,]),'CLOSERANGE':([13,14,30,35,37,38,],[-22,-23,34,-21,39,40,]),'CLOSEINTERVAL':([13,14,31,32,],[-22,-23,35,36,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sentence':([0,],[1,]),'args':([2,],[3,]),'kwargs':([2,3,],[4,19,]),'arg':([2,3,12,],[5,20,22,]),'kwarg':([2,3,4,19,],[6,6,21,21,]),'number':([2,3,12,15,16,17,27,28,29,33,],[8,8,8,23,24,25,30,31,32,37,]),'crange':([2,3,12,],[9,9,9,]),'rinterval':([2,3,12,33,],[10,10,10,38,]),'grinterval':([2,3,12,],[11,11,11,]),'kwflag':([2,3,4,19,],[12,12,12,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sentence","S'",1,None,None,None),
  ('sentence -> VNAME','sentence',1,'p_sentence','parser.py',8),
  ('sentence -> VNAME args','sentence',2,'p_sentence','parser.py',9),
  ('sentence -> VNAME kwargs','sentence',2,'p_sentence','parser.py',10),
  ('sentence -> VNAME args kwargs','sentence',3,'p_sentence','parser.py',11),
  ('kwargs -> kwargs kwarg','kwargs',2,'p_kwargs','parser.py',36),
  ('kwargs -> kwarg','kwargs',1,'p_kwargs','parser.py',37),
  ('kwarg -> kwflag','kwarg',1,'p_kwarg','parser.py',50),
  ('kwarg -> kwflag arg','kwarg',2,'p_kwarg','parser.py',51),
  ('kwflag -> KWSIGN VNAME','kwflag',2,'p_kwflag','parser.py',66),
  ('args -> args arg','args',2,'p_args','parser.py',72),
  ('args -> arg','args',1,'p_args','parser.py',73),
  ('arg -> STRING','arg',1,'p_arg','parser.py',88),
  ('arg -> number','arg',1,'p_arg','parser.py',89),
  ('arg -> crange','arg',1,'p_arg','parser.py',90),
  ('arg -> rinterval','arg',1,'p_arg','parser.py',91),
  ('arg -> grinterval','arg',1,'p_arg','parser.py',92),
  ('crange -> OPENRANGE number GROUPSPLITTER number GROUPSPLITTER rinterval CLOSERANGE','crange',7,'p_crange','parser.py',99),
  ('crange -> OPENRANGE number GROUPSPLITTER number GROUPSPLITTER number CLOSERANGE','crange',7,'p_crange','parser.py',100),
  ('crange -> OPENRANGE number GROUPSPLITTER number CLOSERANGE','crange',5,'p_crange','parser.py',101),
  ('grinterval -> GOPENINTERVAL number GROUPSPLITTER number CLOSEINTERVAL','grinterval',5,'p_grinterval','parser.py',110),
  ('rinterval -> OPENINTERVAL number GROUPSPLITTER number CLOSEINTERVAL','rinterval',5,'p_rinterval','parser.py',117),
  ('number -> INTEGER','number',1,'p_number','parser.py',126),
  ('number -> FLOAT','number',1,'p_number','parser.py',127),
]
